name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync files to cPanel
      run: |
        rsync -avz --delete --exclude '.git*' ./public_html/ wjuhsh6x6mmj@ftp.lucferrara.com:/home/wjuhsh6x6mmj/public_html/
      env:
        SSH_KNOWN_HOSTS: ftp.lucferrara.com
